desk <number_small>: user.desktop(number_small)
desk right: user.desktop_next()
desk left: user.desktop_last()
desk show: user.desktop_show()
window move desk <number>: user.window_move_desktop(number)
window move desk left: user.window_move_desktop_left()
window move desk right: user.window_move_desktop_right()
show desktop: user.desktop_show_base()